### ISSUE TITLE
(feat) Auto-switch to infinite when threshold set

### ISSUE THREAD

**Issue by JaredTamana** [russjr08/Caffeinate#3]
In LineageOS (and predecessors/forks), the Caffeine tile had a really neat feature where you could keep tapping it add time, up to 30 minutes. Once it passed 30 minutes, it would switch to infinite caffeine. Caffeinated has the former, but not the latter. This does not have to be default behaviour and can instead be a setting toggle.

I'm unfamiliar with Kotlin, but if I have some time I might toy around and see if I can get a pull request going.

**Comment by russjr08** [comment]
👋 Hi there, and thanks for reaching out! 

Just to make sure I understand correctly (I've just woken up, so my brain is still a bit on the groggy side 😅), you're looking to have an option added in that will allow the user to adjust the max-threshold of time that can be added before Caffeinate switches to its infinite mode?

If so, that shouldn't be too much to add - Caffeinate does this already, but at one hour instead of 30 minutes, due to a [hardcoded value](https://github.com/russjr08/Caffeinate/blob/master/app/src/main/java/xyz/omnicron/caffeinate/services/CaffeinationService.kt#L206) so it'd just need to be switched over to a value that can be retrieved via a [SharedPreference](https://developer.android.com/reference/android/content/SharedPreferences) so long as I've gathered the details properly here!

> I'm unfamiliar with Kotlin, but if I have some time I might toy around and see if I can get a pull request going.

If you'd like to do so as a learning experience (Kotlin is quite awesome!) then I of course have no issue with that - side effects from this though might include a touch of insanity as Caffeinate's code-base definitely needs an overhaul at some point. The origin story of Caffeinate is that back when Android Nougat came out I wanted to mess around with the Quick Settings API (and to learn more about Kotlin, funnily enough), and when I got it to all work I published it as a "Why not" sort of thing. While I never intended it to become even remotely popular it does make me incredibly happy to see that others have/do benefit from it - the downside to all of this is that the code never left a "MVP" / prototyping state and is definitely more on the messier side.

That is all to say, should you want to give it a go and need to throw in the towel (whether for time-related reasons or said side effect of insanity becomes too much) let me know and I can probably get it all put together relatively soon - or if you do end up giving it a try and have any questions, please don't hesitate to let me know! 👍🏼

**Comment by russjr08** [comment]
This has now been implemented in release [v3.6](https://github.com/russjr08/Caffeinate/releases/tag/v3.6) and will be rolling out to Google Play shortly (once it has been reviewed by Google)!

**Comment by JaredTamana** [comment]
That was quick. Well done!
